# Site settings
title: tyle
email: contact@tyle.io
description: |
  타일은 카드뉴스를 알아서 디자인해주는 카드뉴스 자동 제작 툴입니다.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.tyle.io" # the base hostname & protocol for your site

github_username: tyleteam 

timezone: Asia/Seoul

repository: tyleteam/tyleteam.github.io

permalink: /:categories/:title/

# Build settings
markdown: kramdown

krandown:
  input: GFM
  highlighter: rouge

gems: 
  - jekyll-paginate
  - jekyll-paginate-categories

collections:
  author:
    output: true
    permalink: /authors/:path/
  tags:
    output: true
    permalink: /tags/:path/

defaults:
  - scope:
      path: ''
      type: authors
    values:
      layout: author
  - scope:
      path: ''
      type: tags
    values:
      layout: tag

categories: [tech, marketing]

paginate: 5

paginate_path: '/page/:num'

paginate_category_basepath: '/:name/'
paginate_category_layout: 'categories.html'


exclude: [README.md, Gemfile, Gemfile.lock]

keep_files: [assets]

author: contact@tyle.io

asset_url: /assets

facebook_id : '581242482053180'
